/*
 * Copyright Elasticsearch B.V. and/or licensed to Elasticsearch B.V. under one
 * or more contributor license agreements. Licensed under the "Elastic License
 * 2.0", the "GNU Affero General Public License v3.0 only", and the "Server Side
 * Public License v 1"; you may not use this file except in compliance with, at
 * your election, the "Elastic License 2.0", the "GNU Affero General Public
 * License v3.0 only", or the "Server Side Public License, v 1".
 */

import org.gradle.language.cpp.tasks.CppCompile
import org.gradle.nativeplatform.Linkage

plugins {
  id 'cpp-library'
}

library {
  baseName = 'esql_eval'
  linkage = [Linkage.SHARED]
  source.from fileTree('org/elasticsearch/nativeaccess') {
    include '**/*.cpp'
  }
  privateHeaders.from file('org/elasticsearch/nativeaccess')
}

tasks.withType(CppCompile).configureEach {
  macros.put('ESQL_EVAL_BUILDING_LIBRARY', '1')
}
